from __future__ import annotations

from typing import Any
from unittest.mock import MagicMock

import pytest

from exact_online_sdk.api.endpoints import (
    AbsenceRegistrationsAPI,
    AbsenceRegistrationTransactionsAPI,
    AccountantInfoAPI,
    AccountClassesAPI,
    AccountClassificationNamesAPI,
    AccountClassificationsAPI,
    AccountInvolvedAccountsAPI,
    AccountOwnersAPI,
    AccountsAPI,
    AddressesAPI,
    AddressStatesAPI,
    AllDivisionsAPI,
    AllocationRuleAPI,
    AssemblyBillOfMaterialHeaderAPI,
    AssemblyBillOfMaterialMaterialsAPI,
    AssemblyOrdersAPI,
    AssetGroupsAPI,
    AssetsAPI,
    AvailableFeaturesAPI,
    BankAccountsAPI,
    BankEntriesAPI,
    BankEntryLinesAPI,
    BanksAPI,
    BaseAPI,
    BatchNumbersAPI,
    BillOfMaterialMaterialsAPI,
    BillOfMaterialVersionsAPI,
    BlockedProjectPurchasesAPI,
    BlockedProjectSalesAPI,
    BudgetsAPI,
    BudgetScenariosAPI,
    BulkCashflowPaymentsAPI,
    BulkCashflowReceivablesAPI,
    BulkCRMAccountsAPI,
    BulkCRMAddressesAPI,
    BulkCRMContactsAPI,
    BulkCRMQuotationLinesAPI,
    BulkCRMQuotationsAPI,
    BulkDocumentAttachmentsAPI,
    BulkDocumentsAPI,
    BulkFinancialGLAccountsAPI,
    BulkFinancialGLClassificationsAPI,
    BulkFinancialTransactionLinesAPI,
    BulkLogisticsItemsAPI,
    BulkLogisticsSalesItemPricesAPI,
    BulkProjectProjectWBSAPI,
    BulkSalesInvoiceSalesInvoiceLinesAPI,
    BulkSalesInvoiceSalesInvoicesAPI,
    BulkSalesOrderGoodsDeliveriesAPI,
    BulkSalesOrderGoodsDeliveryLinesAPI,
    BulkSalesOrderSalesOrderLinesAPI,
    BulkSalesOrderSalesOrdersAPI,
    ByProductsAPI,
    CashEntriesAPI,
    CashEntryLinesAPI,
    CommercialBuildingValuesAPI,
    CommunicationNotesAPI,
    ComplaintsAPI,
    ContactsAPI,
    CostcentersAPI,
    CostsByDateAPI,
    CostsByIdAPI,
    CostTypesAPI,
    CostunitsAPI,
    CRMOpportunitiesAPI,
    CRMQuotationLinesAPI,
    CRMQuotationOrderChargeLinesAPI,
    CRMQuotationsAPI,
    CRMReasonCodesAPI,
    CurrenciesAPI,
    CustomerItemsAPI,
    DeductibilityPercentagesAPI,
    DepartmentsAPI,
    DepreciationMethodsAPI,
    DirectDebitMandatesAPI,
    DivisionClassesAPI,
    DivisionClassNamesAPI,
    DivisionClassValuesAPI,
    DivisionsAPI,
    DocumentAttachmentsAPI,
    DocumentCategoriesAPI,
    DocumentFoldersAPI,
    DocumentsAPI,
    DocumentTypeCategoriesAPI,
    DocumentTypeFoldersAPI,
    DocumentTypesAPI,
    DropShipmentLinesAPI,
    DropShipmentsAPI,
    EmploymentActiveEmploymentsAPI,
    EmploymentConditionGroupsAPI,
    EmploymentContractsAPI,
    EmploymentInternalRatesAPI,
    EmploymentOrganizationalUnitsAPI,
    EmploymentSalariesAPI,
    EmploymentsAPI,
    EmploymentStepsAPI,
    EmploymentTaxAuthoritiesGeneralAPI,
    EmploymentTermsAPI,
    EmploymentWorkingHoursAPI,
    EventsAPI,
    ExchangeRatesAPI,
    ExpenseReportsAPI,
    ExpensesAPI,
    FinancialPeriodsAPI,
    GeneralJournalEntriesAPI,
    GeneralJournalEntryLinesAPI,
    GetMostRecentlyUsedDivisionsAPI,
    GLAccountClassificationMappingsAPI,
    GLAccountsAPI,
    GLClassificationsAPI,
    GLSchemesAPI,
    GLTransactionSourcesAPI,
    GLTransactionTypesAPI,
    GoodsDeliveriesAPI,
    GoodsDeliveryLinesAPI,
    HourCostTypesAPI,
    HoursByDateAPI,
    HourTypeBudgetsAPI,
    HourTypesAPI,
    IncotermsAPI,
    InvolvedUserRolesAPI,
    InvolvedUsersAPI,
    ItemAssortmentAPI,
    ItemAssortmentPropertyAPI,
    ItemChargeRelationAPI,
    ItemGroupsAPI,
    ItemMaterialsPlanningAPI,
    ItemsAPI,
    ItemVersionsAPI,
    ItemWarehousePlanningDetailsAPI,
    ItemWarehousesAPI,
    ItemWarehouseStorageLocationsAPI,
    JobGroupsAPI,
    JobTitlesAPI,
    JournalsAPI,
    LayoutsAPI,
    LeadPurposesAPI,
    LeadSourcesAPI,
    LeaveAbsenceHoursByDayAPI,
    LeaveBuildUpRegistrationsAPI,
    LeaveRegistrationsAPI,
    LogisticsReasonCodesAPI,
    MailboxesAPI,
    MailMessageAttachmentsAPI,
    MailMessagesSentAPI,
    MaterialReversalsAPI,
    MeAPI,
    OfficialReturnsAPI,
    OperationResourcesAPI,
    OperationsAPI,
    OpportunitiesAPI,
    OpportunityContactsAPI,
    PaymentConditionsAPI,
    PaymentsAPI,
    PlannedSalesReturnLinesAPI,
    PlannedSalesReturnsAPI,
    PlannedShopOrdersAPI,
    PlanningReleasesAPI,
    ProductionAreasAPI,
    ProductionOrdersAPI,
    ProjectClassificationsAPI,
    ProjectHourBudgetsAPI,
    ProjectPlanningAPI,
    ProjectPlanningRecurringAPI,
    ProjectsAPI,
    PurchaseOrderLinesAPI,
    PurchaseOrdersAPI,
    QuotationLinesAPI,
    QuotationsAPI,
    ReasonCodesLinkTypesAPI,
    ReceivablesAPI,
    ReportingBalanceAPI,
    RequestAttachmentsAPI,
    SalesInvoiceLinesAPI,
    SalesInvoiceOrderChargeLinesAPI,
    SalesInvoicesAPI,
    SalesItemPricesAPI,
    SalesOrderLinesAPI,
    SalesOrderOrderChargeLinesAPI,
    SalesOrdersAPI,
    SchedulesAPI,
    SelectionCodesAPI,
    ServiceRequestsAPI,
    ShopOrderMaterialPlansAPI,
    ShopOrderRoutingStepPlansAPI,
    ShopOrdersAPI,
    SolutionLinksAPI,
    StockBatchNumbersAPI,
    StockCountLinesAPI,
    StockCountsAPI,
    StockSerialNumbersAPI,
    StorageLocationsAPI,
    SubOrderReversalsAPI,
    SubscriptionLinesAPI,
    SubscriptionLineTypesAPI,
    SubscriptionReasonCodesAPI,
    SubscriptionRestrictionEmployeesAPI,
    SubscriptionRestrictionItemsAPI,
    SubscriptionsAPI,
    SubscriptionTypesAPI,
    SupplierItemAPI,
    SyncCashflowPaymentTermsAPI,
    SyncCRMAccountsAPI,
    SyncCRMAddressesAPI,
    SyncCRMContactsAPI,
    SyncCRMQuotationHeadersAPI,
    SyncCRMQuotationLinesAPI,
    SyncDocumentAttachmentsAPI,
    SyncDocumentsAPI,
    SyncFinancialGLAccountsAPI,
    SyncFinancialGLClassificationsAPI,
    SyncFinancialTransactionLinesAPI,
    SyncHRMAbsenceRegistrationsAPI,
    SyncHRMAbsenceRegistrationTransactionsAPI,
    SyncHRMLeaveAbsenceHoursByDayAPI,
    SyncHRMLeaveBuildUpRegistrationsAPI,
    SyncHRMLeaveRegistrationsAPI,
    SyncHRMScheduleEntriesAPI,
    SyncHRMSchedulesAPI,
    SyncInventoryItemStorageLocationsAPI,
    SyncInventoryItemWarehousesAPI,
    SyncInventorySerialBatchNumbersAPI,
    SyncInventoryStockPositionsAPI,
    SyncInventoryStockSerialBatchNumbersAPI,
    SyncInventoryStorageLocationStockPositionsAPI,
    SyncLogisticsItemsAPI,
    SyncLogisticsPurchaseItemPricesAPI,
    SyncLogisticsSalesItemPricesAPI,
    SyncLogisticsSupplierItemAPI,
    SyncManufacturingBillOfMaterialMaterialsAPI,
    SyncManufacturingBillOfMaterialVersionsAPI,
    SyncManufacturingMaterialIssuesAPI,
    SyncManufacturingShopOrderMaterialPlansAPI,
    SyncManufacturingShopOrderPurchasePlanningAPI,
    SyncManufacturingShopOrderRoutingStepPlansAPI,
    SyncManufacturingShopOrdersAPI,
    SyncManufacturingShopOrderSubOrdersAPI,
    SyncPayrollBankAccountsAPI,
    SyncPayrollEmployeesAPI,
    SyncPayrollEmploymentCLAsAPI,
    SyncPayrollEmploymentContractsAPI,
    SyncPayrollEmploymentOrganizationsAPI,
    SyncPayrollEmploymentSalariesAPI,
    SyncPayrollEmploymentsAPI,
    SyncPayrollEmploymentTaxAuthoritiesGeneralAPI,
    SyncProjectProjectPlanningAPI,
    SyncProjectProjectsAPI,
    SyncProjectProjectWBSAPI,
    SyncProjectTimeCostTransactionsAPI,
    SyncPurchaseOrderPurchaseOrdersAPI,
    SyncSalesInvoiceSalesInvoicesAPI,
    SyncSalesOrderGoodsDeliveriesAPI,
    SyncSalesOrderGoodsDeliveryLinesAPI,
    SyncSalesOrderSalesOrderHeadersAPI,
    SyncSalesOrderSalesOrderLinesAPI,
    SyncSalesSalesPriceListVolumeDiscountsAPI,
    SyncSubscriptionSubscriptionLinesAPI,
    SyncSubscriptionSubscriptionsAPI,
    SystemDivisionsAPI,
    TasksAPI,
    TaskTypesAPI,
    TimeAndBillingEntryAccountsAPI,
    TransactionLinesAPI,
    UnitsAPI,
    UserRolesAPI,
    UserRolesPerDivisionAPI,
    VATCodesAPI,
    VatPercentagesAPI,
    WarehousesAPI,
    WarehouseTransferLinesAPI,
    WarehouseTransfersAPI,
    WebhookSubscriptionsAPI,
)


class DummyAPI(BaseAPI):
    def _resource(self) -> str:
        return "crm/Accounts"


class DummySkipDivisionAPI(BaseAPI):
    _skip_division: bool = True

    def _resource(self) -> str:
        return "current/Me"


def test_skip_division_flag_prefixes_bang() -> None:
    client = MagicMock()
    api = DummySkipDivisionAPI(client)
    assert api._get_resource_path() == "!current/Me"


def test_default_skip_division_is_false() -> None:
    client = MagicMock()
    api = DummyAPI(client)
    assert api._get_resource_path() == "crm/Accounts"


def test_me_api_skip_division() -> None:
    client = MagicMock()
    client.get.return_value = [{"CurrentDivision": 123}]
    api = MeAPI(client)
    api.list()
    client.get.assert_called_with("!current/Me", params=None)


def test_base_api_delegates_to_client_methods() -> None:
    client = MagicMock()
    api = DummyAPI(client)

    client.get.return_value = [{"ID": "1"}]
    client.post.return_value = {"ID": "1"}
    client.patch.return_value = {"ID": "1"}
    client.delete.return_value = None

    assert api.list(params={"$top": 1}) == [{"ID": "1"}]
    client.get.assert_called_with("crm/Accounts", params={"$top": 1})

    assert api.get("abc") == [{"ID": "1"}]
    client.get.assert_called_with("crm/Accounts(guid'abc')")

    payload = {"Name": "Test"}
    assert api.create(payload) == {"ID": "1"}
    client.post.assert_called_with("crm/Accounts", json=payload)

    assert api.update("abc", payload) == {"ID": "1"}
    client.patch.assert_called_with("crm/Accounts(guid'abc')", json=payload)

    assert api.delete("abc") is None
    client.delete.assert_called_with("crm/Accounts(guid'abc')")


@pytest.mark.parametrize(
    ("api_cls", "expected_resource"),
    [
        (AccountsAPI, "crm/Accounts"),
        (ContactsAPI, "crm/Contacts"),
        (SalesOrdersAPI, "salesorder/SalesOrders"),
        (ItemsAPI, "logistics/Items"),
        (SalesInvoicesAPI, "salesinvoice/SalesInvoices"),
        (BulkCRMAccountsAPI, "bulk/CRM/Accounts"),
        (BulkCRMAddressesAPI, "bulk/CRM/Addresses"),
        (BulkCRMContactsAPI, "bulk/CRM/Contacts"),
        (BulkCRMQuotationLinesAPI, "bulk/CRM/QuotationLines"),
        (BulkCRMQuotationsAPI, "bulk/CRM/Quotations"),
        (BulkDocumentAttachmentsAPI, "bulk/Documents/DocumentAttachments"),
        (BulkDocumentsAPI, "bulk/Documents/Documents"),
        (AccountClassesAPI, "crm/AccountClasses"),
        (AccountClassificationNamesAPI, "crm/AccountClassificationNames"),
        (AccountClassificationsAPI, "crm/AccountClassifications"),
        (AddressesAPI, "crm/Addresses"),
        (SyncCRMAddressesAPI, "sync/CRM/Addresses"),
        (AddressStatesAPI, "crm/AddressStates"),
        (BankAccountsAPI, "crm/BankAccounts"),
        (LeadPurposesAPI, "crm/LeadPurposes"),
        (LeadSourcesAPI, "crm/LeadSources"),
        (SyncCRMContactsAPI, "sync/CRM/Contacts"),
        (CRMOpportunitiesAPI, "crm/Opportunities"),
        (CRMQuotationLinesAPI, "crm/QuotationLines"),
        (CRMQuotationOrderChargeLinesAPI, "crm/QuotationOrderChargeLines"),
        (CRMQuotationsAPI, "crm/Quotations"),
        (CRMReasonCodesAPI, "crm/ReasonCodes"),
        (DocumentAttachmentsAPI, "documents/DocumentAttachments"),
        (DocumentCategoriesAPI, "documents/DocumentCategories"),
        (DocumentFoldersAPI, "documents/DocumentFolders"),
        (DocumentTypeCategoriesAPI, "documents/DocumentTypeCategories"),
        (DocumentTypeFoldersAPI, "documents/DocumentTypeFolders"),
        (DocumentTypesAPI, "documents/DocumentTypes"),
        (DocumentsAPI, "documents/Documents"),
        (GLAccountsAPI, "financial/GLAccounts"),
        (BulkFinancialGLAccountsAPI, "bulk/Financial/GLAccounts"),
        (SyncFinancialGLAccountsAPI, "sync/Financial/GLAccounts"),
        (AssemblyBillOfMaterialHeaderAPI, "inventory/AssemblyBillOfMaterialHeader"),
        (
            AssemblyBillOfMaterialMaterialsAPI,
            "inventory/AssemblyBillOfMaterialMaterials",
        ),
        (AssemblyOrdersAPI, "inventory/AssemblyOrders"),
        (BatchNumbersAPI, "inventory/BatchNumbers"),
        (
            ItemWarehousePlanningDetailsAPI,
            "inventory/ItemWarehousePlanningDetails",
        ),
        (
            ItemWarehouseStorageLocationsAPI,
            "inventory/ItemWarehouseStorageLocations",
        ),
        (ItemWarehousesAPI, "inventory/ItemWarehouses"),
        (StockBatchNumbersAPI, "inventory/StockBatchNumbers"),
        (StockCountLinesAPI, "inventory/StockCountLines"),
        (StockCountsAPI, "inventory/StockCounts"),
        (StockSerialNumbersAPI, "inventory/StockSerialNumbers"),
        (StorageLocationsAPI, "inventory/StorageLocations"),
        (WarehouseTransferLinesAPI, "inventory/WarehouseTransferLines"),
        (WarehouseTransfersAPI, "inventory/WarehouseTransfers"),
        (WarehousesAPI, "inventory/Warehouses"),
        (CustomerItemsAPI, "logistics/CustomerItems"),
        (IncotermsAPI, "logistics/Incoterms"),
        (ItemAssortmentAPI, "logistics/ItemAssortment"),
        (ItemAssortmentPropertyAPI, "logistics/ItemAssortmentProperty"),
        (ItemChargeRelationAPI, "logistics/ItemChargeRelation"),
        (ItemGroupsAPI, "logistics/ItemGroups"),
        (ItemVersionsAPI, "logistics/ItemVersions"),
        (LogisticsReasonCodesAPI, "logistics/ReasonCodes"),
        (ReasonCodesLinkTypesAPI, "logistics/ReasonCodesLinkTypes"),
        (SalesItemPricesAPI, "logistics/SalesItemPrices"),
        (SelectionCodesAPI, "logistics/SelectionCodes"),
        (SupplierItemAPI, "logistics/SupplierItem"),
        (UnitsAPI, "logistics/Units"),
        (OpportunityContactsAPI, "opportunities/OpportunityContacts"),
        (OpportunitiesAPI, "opportunities/Opportunities"),
        (PurchaseOrderLinesAPI, "purchase/PurchaseOrderLines"),
        (PurchaseOrdersAPI, "purchase/PurchaseOrders"),
        (QuotationLinesAPI, "quotation/QuotationLines"),
        (QuotationsAPI, "quotation/Quotations"),
        (SalesInvoiceLinesAPI, "salesinvoice/SalesInvoiceLines"),
        (SalesInvoiceOrderChargeLinesAPI, "salesinvoice/SalesInvoiceOrderChargeLines"),
        (DropShipmentLinesAPI, "salesorder/DropShipmentLines"),
        (DropShipmentsAPI, "salesorder/DropShipments"),
        (GoodsDeliveriesAPI, "salesorder/GoodsDeliveries"),
        (GoodsDeliveryLinesAPI, "salesorder/GoodsDeliveryLines"),
        (PlannedSalesReturnLinesAPI, "salesorder/PlannedSalesReturnLines"),
        (PlannedSalesReturnsAPI, "salesorder/PlannedSalesReturns"),
        (SalesOrderLinesAPI, "salesorder/SalesOrderLines"),
        (SalesOrderOrderChargeLinesAPI, "salesorder/SalesOrderOrderChargeLines"),
        (
            SyncInventoryItemStorageLocationsAPI,
            "sync/Inventory/ItemStorageLocations",
        ),
        (SyncInventoryItemWarehousesAPI, "sync/Inventory/ItemWarehouses"),
        (SyncInventorySerialBatchNumbersAPI, "sync/Inventory/SerialBatchNumbers"),
        (SyncInventoryStockPositionsAPI, "sync/Inventory/StockPositions"),
        (
            SyncInventoryStockSerialBatchNumbersAPI,
            "sync/Inventory/StockSerialBatchNumbers",
        ),
        (
            SyncInventoryStorageLocationStockPositionsAPI,
            "sync/Inventory/StorageLocationStockPositions",
        ),
        (SyncDocumentAttachmentsAPI, "sync/Documents/DocumentAttachments"),
        (SyncDocumentsAPI, "sync/Documents/Documents"),
        (AccountInvolvedAccountsAPI, "accountancy/AccountInvolvedAccounts"),
        (AccountOwnersAPI, "accountancy/AccountOwners"),
        (InvolvedUserRolesAPI, "accountancy/InvolvedUserRoles"),
        (InvolvedUsersAPI, "accountancy/InvolvedUsers"),
        (SolutionLinksAPI, "accountancy/SolutionLinks"),
        (TaskTypesAPI, "accountancy/TaskTypes"),
        (CommunicationNotesAPI, "activities/CommunicationNotes"),
        (ComplaintsAPI, "activities/Complaints"),
        (EventsAPI, "activities/Events"),
        (ServiceRequestsAPI, "activities/ServiceRequests"),
        (TasksAPI, "activities/Tasks"),
        (AssetGroupsAPI, "assets/AssetGroups"),
        (AssetsAPI, "assets/Assets"),
        (CommercialBuildingValuesAPI, "assets/CommercialBuildingValues"),
        (DepreciationMethodsAPI, "assets/DepreciationMethods"),
        (BudgetsAPI, "budget/Budgets"),
        (BudgetScenariosAPI, "beta/{division}/budget/BudgetScenarios"),
        (AllocationRuleAPI, "beta/{division}/cashflow/AllocationRule"),
        (BanksAPI, "cashflow/Banks"),
        (DirectDebitMandatesAPI, "cashflow/DirectDebitMandates"),
        (PaymentConditionsAPI, "cashflow/PaymentConditions"),
        (PaymentsAPI, "cashflow/Payments"),
        (ReceivablesAPI, "cashflow/Receivables"),
        (
            EmploymentConditionGroupsAPI,
            "beta/{division}/payroll/EmploymentConditionGroups",
        ),
        (RequestAttachmentsAPI, "beta/{division}/workflow/RequestAttachments"),
        (GLClassificationsAPI, "financial/GLClassifications"),
        (TransactionLinesAPI, "financialtransaction/TransactionLines"),
        (BulkCashflowPaymentsAPI, "bulk/Cashflow/Payments"),
        (BulkCashflowReceivablesAPI, "bulk/Cashflow/Receivables"),
        (BulkFinancialGLClassificationsAPI, "bulk/Financial/GLClassifications"),
        (BulkFinancialTransactionLinesAPI, "bulk/Financial/TransactionLines"),
        (BulkLogisticsItemsAPI, "bulk/Logistics/Items"),
        (BulkLogisticsSalesItemPricesAPI, "bulk/Logistics/SalesItemPrices"),
        (BulkProjectProjectWBSAPI, "bulk/Project/ProjectWBS"),
        (BulkSalesInvoiceSalesInvoiceLinesAPI, "bulk/SalesInvoice/SalesInvoiceLines"),
        (BulkSalesInvoiceSalesInvoicesAPI, "bulk/SalesInvoice/SalesInvoices"),
        (BulkSalesOrderGoodsDeliveriesAPI, "bulk/SalesOrder/GoodsDeliveries"),
        (BulkSalesOrderGoodsDeliveryLinesAPI, "bulk/SalesOrder/GoodsDeliveryLines"),
        (BulkSalesOrderSalesOrderLinesAPI, "bulk/SalesOrder/SalesOrderLines"),
        (BulkSalesOrderSalesOrdersAPI, "bulk/SalesOrder/SalesOrders"),
        (ExpenseReportsAPI, "expensemanagement/ExpenseReports"),
        (ExpensesAPI, "expensemanagement/Expenses"),
        (DeductibilityPercentagesAPI, "financial/DeductibilityPercentages"),
        (ExchangeRatesAPI, "financial/ExchangeRates"),
        (FinancialPeriodsAPI, "financial/FinancialPeriods"),
        (
            GLAccountClassificationMappingsAPI,
            "financial/GLAccountClassificationMappings",
        ),
        (GLSchemesAPI, "financial/GLSchemes"),
        (GLTransactionSourcesAPI, "financial/GLTransactionSources"),
        (GLTransactionTypesAPI, "financial/GLTransactionTypes"),
        (JournalsAPI, "financial/Journals"),
        (OfficialReturnsAPI, "financial/OfficialReturns"),
        (ReportingBalanceAPI, "financial/ReportingBalance"),
        (BankEntriesAPI, "financialtransaction/BankEntries"),
        (BankEntryLinesAPI, "financialtransaction/BankEntryLines"),
        (CashEntriesAPI, "financialtransaction/CashEntries"),
        (CashEntryLinesAPI, "financialtransaction/CashEntryLines"),
        (CurrenciesAPI, "general/Currencies"),
        (LayoutsAPI, "general/Layouts"),
        (GeneralJournalEntriesAPI, "generaljournalentry/GeneralJournalEntries"),
        (
            GeneralJournalEntryLinesAPI,
            "generaljournalentry/GeneralJournalEntryLines",
        ),
        (AbsenceRegistrationsAPI, "hrm/AbsenceRegistrations"),
        (
            AbsenceRegistrationTransactionsAPI,
            "hrm/AbsenceRegistrationTransactions",
        ),
        (CostcentersAPI, "hrm/Costcenters"),
        (CostunitsAPI, "hrm/Costunits"),
        (DepartmentsAPI, "hrm/Departments"),
        (DivisionClassesAPI, "hrm/DivisionClasses"),
        (DivisionClassNamesAPI, "hrm/DivisionClassNames"),
        (DivisionClassValuesAPI, "hrm/DivisionClassValues"),
        (DivisionsAPI, "hrm/Divisions"),
        (JobGroupsAPI, "hrm/JobGroups"),
        (JobTitlesAPI, "hrm/JobTitles"),
        (LeaveAbsenceHoursByDayAPI, "hrm/LeaveAbsenceHoursByDay"),
        (LeaveBuildUpRegistrationsAPI, "hrm/LeaveBuildUpRegistrations"),
        (LeaveRegistrationsAPI, "hrm/LeaveRegistrations"),
        (SchedulesAPI, "hrm/Schedules"),
        (SyncCRMAccountsAPI, "sync/CRM/Accounts"),
        (SyncCRMQuotationHeadersAPI, "sync/CRM/QuotationHeaders"),
        (SyncCRMQuotationLinesAPI, "sync/CRM/QuotationLines"),
        (SyncCashflowPaymentTermsAPI, "sync/Cashflow/PaymentTerms"),
        (
            SyncFinancialGLClassificationsAPI,
            "sync/Financial/GLClassifications",
        ),
        (SyncFinancialTransactionLinesAPI, "sync/Financial/TransactionLines"),
        (
            SyncHRMAbsenceRegistrationTransactionsAPI,
            "sync/HRM/AbsenceRegistrationTransactions",
        ),
        (SyncHRMAbsenceRegistrationsAPI, "sync/HRM/AbsenceRegistrations"),
        (SyncHRMLeaveAbsenceHoursByDayAPI, "sync/HRM/LeaveAbsenceHoursByDay"),
        (
            SyncHRMLeaveBuildUpRegistrationsAPI,
            "sync/HRM/LeaveBuildUpRegistrations",
        ),
        (SyncHRMLeaveRegistrationsAPI, "sync/HRM/LeaveRegistrations"),
        (SyncHRMSchedulesAPI, "sync/HRM/Schedules"),
        (SyncLogisticsItemsAPI, "sync/Logistics/Items"),
        (SyncLogisticsSalesItemPricesAPI, "sync/Logistics/SalesItemPrices"),
        (SyncLogisticsSupplierItemAPI, "sync/Logistics/SupplierItem"),
        (SyncPayrollBankAccountsAPI, "sync/Payroll/BankAccounts"),
        (SyncProjectProjectWBSAPI, "sync/Project/ProjectWBS"),
        (
            SyncPurchaseOrderPurchaseOrdersAPI,
            "sync/PurchaseOrder/PurchaseOrders",
        ),
        (SyncSalesInvoiceSalesInvoicesAPI, "sync/SalesInvoice/SalesInvoices"),
        (SyncSalesOrderGoodsDeliveriesAPI, "sync/SalesOrder/GoodsDeliveries"),
        (
            SyncSalesOrderGoodsDeliveryLinesAPI,
            "sync/SalesOrder/GoodsDeliveryLines",
        ),
        (SyncSalesOrderSalesOrderHeadersAPI, "sync/SalesOrder/SalesOrderHeaders"),
        (SyncSalesOrderSalesOrderLinesAPI, "sync/SalesOrder/SalesOrderLines"),
        (SystemDivisionsAPI, "system/Divisions"),
        (MeAPI, "!current/Me"),
        (MailMessageAttachmentsAPI, "mailbox/MailMessageAttachments"),
        (MailMessagesSentAPI, "mailbox/MailMessagesSent"),
        (MailboxesAPI, "mailbox/Mailboxes"),
        (BillOfMaterialMaterialsAPI, "manufacturing/BillOfMaterialMaterials"),
        (BillOfMaterialVersionsAPI, "manufacturing/BillOfMaterialVersions"),
        (ByProductsAPI, "manufacturing/ByProducts"),
        (ItemMaterialsPlanningAPI, "manufacturing/ItemMaterialsPlanning"),
        (MaterialReversalsAPI, "manufacturing/MaterialReversals"),
        (OperationResourcesAPI, "manufacturing/OperationResources"),
        (OperationsAPI, "manufacturing/Operations"),
        (PlannedShopOrdersAPI, "manufacturing/PlannedShopOrders"),
        (PlanningReleasesAPI, "manufacturing/PlanningReleases"),
        (ProductionAreasAPI, "manufacturing/ProductionAreas"),
        (ProductionOrdersAPI, "manufacturing/ProductionOrders"),
        (ShopOrderMaterialPlansAPI, "manufacturing/ShopOrderMaterialPlans"),
        (
            ShopOrderRoutingStepPlansAPI,
            "manufacturing/ShopOrderRoutingStepPlans",
        ),
        (ShopOrdersAPI, "manufacturing/ShopOrders"),
        (SubOrderReversalsAPI, "manufacturing/SubOrderReversals"),
        (
            EmploymentActiveEmploymentsAPI,
            "payroll/EmploymentActiveEmployments",
        ),
        (EmploymentContractsAPI, "payroll/EmploymentContracts"),
        (
            EmploymentOrganizationalUnitsAPI,
            "payroll/EmploymentOrganizationalUnits",
        ),
        (EmploymentSalariesAPI, "payroll/EmploymentSalaries"),
        (EmploymentStepsAPI, "payroll/EmploymentSteps"),
        (
            EmploymentTaxAuthoritiesGeneralAPI,
            "payroll/EmploymentTaxAuthoritiesGeneral",
        ),
        (EmploymentTermsAPI, "payroll/EmploymentTerms"),
        (EmploymentWorkingHoursAPI, "payroll/EmploymentWorkingHours"),
        (EmploymentsAPI, "payroll/Employments"),
        (BlockedProjectPurchasesAPI, "project/BlockedProjectPurchases"),
        (BlockedProjectSalesAPI, "project/BlockedProjectSales"),
        (CostTypesAPI, "project/CostTypes"),
        (EmploymentInternalRatesAPI, "project/EmploymentInternalRates"),
        (HourCostTypesAPI, "project/HourCostTypes"),
        (HourTypeBudgetsAPI, "project/HourTypeBudgets"),
        (HourTypesAPI, "project/HourTypes"),
        (ProjectsAPI, "project/Projects"),
        (ProjectClassificationsAPI, "project/ProjectClassifications"),
        (ProjectHourBudgetsAPI, "project/ProjectHourBudgets"),
        (ProjectPlanningAPI, "project/ProjectPlanning"),
        (ProjectPlanningRecurringAPI, "project/ProjectPlanningRecurring"),
        (CostsByDateAPI, "read/project/CostsByDate"),
        (CostsByIdAPI, "read/project/CostsById"),
        (HoursByDateAPI, "read/project/HoursByDate"),
        (
            TimeAndBillingEntryAccountsAPI,
            "projectwbs/TimeAndBillingEntryAccounts",
        ),
        (SubscriptionLineTypesAPI, "subscription/SubscriptionLineTypes"),
        (SubscriptionLinesAPI, "subscription/SubscriptionLines"),
        (SubscriptionReasonCodesAPI, "subscription/SubscriptionReasonCodes"),
        (
            SubscriptionRestrictionEmployeesAPI,
            "subscription/SubscriptionRestrictionEmployees",
        ),
        (
            SubscriptionRestrictionItemsAPI,
            "subscription/SubscriptionRestrictionItems",
        ),
        (SubscriptionTypesAPI, "subscription/SubscriptionTypes"),
        (SubscriptionsAPI, "subscription/Subscriptions"),
        (AccountantInfoAPI, "system/AccountantInfo"),
        (AllDivisionsAPI, "system/AllDivisions"),
        (AvailableFeaturesAPI, "system/AvailableFeatures"),
        (
            GetMostRecentlyUsedDivisionsAPI,
            "system/GetMostRecentlyUsedDivisions",
        ),
        (UserRolesAPI, "users/UserRoles"),
        (UserRolesPerDivisionAPI, "users/UserRolesPerDivision"),
        (VATCodesAPI, "vat/VATCodes"),
        (VatPercentagesAPI, "vat/VatPercentages"),
        (WebhookSubscriptionsAPI, "webhooks/WebhookSubscriptions"),
        (SyncHRMScheduleEntriesAPI, "sync/HRM/ScheduleEntries"),
        (
            SyncLogisticsPurchaseItemPricesAPI,
            "sync/Logistics/PurchaseItemPrices",
        ),
        (
            SyncManufacturingBillOfMaterialMaterialsAPI,
            "sync/Manufacturing/BillOfMaterialMaterials",
        ),
        (
            SyncManufacturingBillOfMaterialVersionsAPI,
            "sync/Manufacturing/BillOfMaterialVersions",
        ),
        (
            SyncManufacturingMaterialIssuesAPI,
            "sync/Manufacturing/MaterialIssues",
        ),
        (
            SyncManufacturingShopOrderMaterialPlansAPI,
            "sync/Manufacturing/ShopOrderMaterialPlans",
        ),
        (
            SyncManufacturingShopOrderPurchasePlanningAPI,
            "sync/Manufacturing/ShopOrderPurchasePlanning",
        ),
        (
            SyncManufacturingShopOrderRoutingStepPlansAPI,
            "sync/Manufacturing/ShopOrderRoutingStepPlans",
        ),
        (
            SyncManufacturingShopOrderSubOrdersAPI,
            "sync/Manufacturing/ShopOrderSubOrders",
        ),
        (SyncManufacturingShopOrdersAPI, "sync/Manufacturing/ShopOrders"),
        (SyncPayrollEmployeesAPI, "sync/Payroll/Employees"),
        (SyncPayrollEmploymentCLAsAPI, "sync/Payroll/EmploymentCLAs"),
        (
            SyncPayrollEmploymentContractsAPI,
            "sync/Payroll/EmploymentContracts",
        ),
        (
            SyncPayrollEmploymentOrganizationsAPI,
            "sync/Payroll/EmploymentOrganizations",
        ),
        (
            SyncPayrollEmploymentSalariesAPI,
            "sync/Payroll/EmploymentSalaries",
        ),
        (
            SyncPayrollEmploymentTaxAuthoritiesGeneralAPI,
            "sync/Payroll/EmploymentTaxAuthoritiesGeneral",
        ),
        (SyncPayrollEmploymentsAPI, "sync/Payroll/Employments"),
        (SyncProjectProjectPlanningAPI, "sync/Project/ProjectPlanning"),
        (SyncProjectProjectsAPI, "sync/Project/Projects"),
        (
            SyncProjectTimeCostTransactionsAPI,
            "sync/Project/TimeCostTransactions",
        ),
        (
            SyncSalesSalesPriceListVolumeDiscountsAPI,
            "sync/Sales/SalesPriceListVolumeDiscounts",
        ),
        (
            SyncSubscriptionSubscriptionLinesAPI,
            "sync/Subscription/SubscriptionLines",
        ),
        (
            SyncSubscriptionSubscriptionsAPI,
            "sync/Subscription/Subscriptions",
        ),
    ],
)
def test_endpoint_list_uses_expected_resource(
    api_cls: Any, expected_resource: str
) -> None:
    client = MagicMock()
    client.get.return_value = []

    api = api_cls(client)

    assert api.list() == []
    client.get.assert_called_with(expected_resource, params=None)
